version: '3.0'

services:
  algod:
    image: algorand/algod:stable
    ports:
      - 8080:8080
    environment:
      TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      ADMIN_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      NETWORK: 'mainnet'
    volumes:
      - ./data:/algod/data
      - ./config.json:/etc/algorand/config.json

  conduit_db:
    image: "postgres:13-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: conduit_db